Create onboarding
GSG-CF04/ToDo-List-06 pull request #8
Opened 2021-11-11 08:34 UTC by kakashii7

create onboarding page and image for onboarding page and css file

2021-11-11 09:24 UTC, ahmedirheem approved these changes, later dismissed
Good job

2021-11-11 10:29 UTC, sara219 requested changes
the assets folder provide a way to add arbitrary files like text, fonts, music, and video in the application, we don't add style and js files into it 
remove the CSS and JS folders from it and put them in the root

2021-11-11 10:29 UTC, sara219 commented on assets/css/style.css
> +        }
there's a file called style.css in the root, why did you create a new one

2021-11-11 10:29 UTC, sara219 commented on index.html
> +            <input id="name" onselect="fun(this)" type="text" name=" " placeholder="Enter your name ">
I think it needs to be more organized, the title, input and button to be in the same level and direction


<img width="327" alt="Screen Shot 2021-11-11 at 12 23 32 PM" src="https://user-images.githubusercontent.com/47992412/141282167-8aa29485-1309-4941-ad7e-7b7ea15a9f5b.png">

2021-11-12 17:12 UTC, ahmedirheem approved these changes, later dismissed

2021-11-13 07:19 UTC, farahalzard approved these changes

2021-11-13 08:26 UTC, ahmedirheem approved these changes

2021-11-13 10:09 UTC, sara219 approved these changes

2021-11-13 10:11 UTC, merged